### ISSUE TITLE
double nav and contact bars

### ISSUE THREAD

**Issue by SeanTomlinson30** [sanjaynagi/sanjaynagi.github.io#1]
Hey Sanj,

This is a cool project to find your way around GH. Happy to help with any of the more fiddly bits you get stuck with relating to GH, braches, issues and PRs. Just let me know :)

I'm sure you know but the build of your site doubles up on the nav bar and contact strip.

A good repo to look at is barryclark/jekyll-now

**Comment by sanjaynagi** [comment]
Hey Sean!
I saw that - I had the navigation bar both in my index.html and my default.html, so it was calling it twice. sorted now. Thanks!!

**Comment by sanjaynagi** [comment]
Closing issue now.. :)
